"""adding followers

Revision ID: 817e47c8c3cf
Revises: a08963b11840
Create Date: 2018-01-28 10:32:10.053240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817e47c8c3cf'
down_revision = 'a08963b11840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
